# Generated by Django 6.1.1 on 2026-10-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_produto_remove_cliente_endereco_padrao_cliente_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(default='sem categoria', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(default='sem categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(default='sem categoria', max_length=20),
            preserve_default=False,
        ),
    ]
